version: "2"

services:

  web:
    build: .
    command: bash -c "python backend/models.py && python backend/main.py"
    ports:
      - "5000:5000"
#    networks:
#      - def
  bank1:
    container_name: bank1
    build: fino-bank
    command: bash -c "python -m swagger_server 8080"
    ports:
      - "8080:8080"
#    networks:
#      - def

  bank2:
    container_name: bank2
    build: fino-bank
    command: bash -c "python -m swagger_server 5467"
    ports:
      - "5467:5467"
#    networks:
#      - def

#networks:
#  def:
#    driver: bridge